### ISSUE TITLE
Thunderbird error: Outgoing server (SMTP) error. The server responded:  * OK IMAP4rev1 Server GreenMail v2.0.0

### ISSUE THREAD

**Issue by usersina** [greenmail-mail-test/greenmail#559]
Using [Thunderbird](https://www.thunderbird.net/en-US/) as my email client and `Greenmail 2.0.0`, I get the following error trying to send an email:

> Sending of the message failed.
An error occurred while sending mail: Outgoing server (SMTP) error. The server responded:  * OK IMAP4rev1 Server GreenMail v2.0.0 ready.

![image](https://github.com/greenmail-mail-test/greenmail/assets/44204957/7deb5a73-308d-480d-a84e-a952998fdecc)

I run Greenmail in docker as follows

```yml
services:
  greenmail:
    image: greenmail/standalone:2.0.0
    container_name: greenmail
    environment:
      GREENMAIL_OPTS: "-Dgreenmail.setup.test.all -Dgreenmail.hostname=0.0.0.0 -Dgreenmail.auth.disabled -Dgreenmail.verbose"
    ports:
      - "5000:8080" # API interface
      - "25:3025" # SMTP
      - "143:3143" # IMAP
      - "110:3110" # POP3
```

Here are the logs in verbose mode

```
2023-06-03 22:49:49 2023-06-03 21:49:49,890 DEBUG           imap.ImapServer| Handling new client connection imap:0.0.0.0:3143<-/192.168.128.1:52456
2023-06-03 22:49:49 2023-06-03 21:49:49,891 DEBUG    util.LineLoggingBuffer| S: * OK IMAP4rev1 Server GreenMail v2.0.0 ready\r\n
2023-06-03 22:49:49 2023-06-03 21:49:49,934 TRACE          imap.ImapHandler| Closing handler connection /192.168.128.1:52456
```

FWIW, here's my Thunderbird configuration:

![image](https://github.com/greenmail-mail-test/greenmail/assets/44204957/06a26717-7c86-4094-bb2d-59ff59238496)
