### ISSUE TITLE
Fix Travis CI OpenJDK 6 / Maven build

### ISSUE THREAD

**Issue by marcelmay** [greenmail-mail-test/greenmail#69]
Travis CI recently upgraded their Maven version to 3.3.1, which breaks with JDK 6.

1. Custom install Maven 3.2.x 
2. Re-enable JDK 1.6 build

**Comment by buildscientist** [comment]
I think this is related to issue #23 

I've looked at the [Java specific feature set](https://circleci.com/docs/environment#java) in CircleCI and I think this fits our requirements. 

I understand that Java 6/7 have both been discontinued but a large number of companies will purchase Oracle support contracts to extend backported bug fixes for those versions. 

We should propose dropping support for Java 6/7 in GreenMail v2.0 - once we complete development of the test API.

**Comment by buildscientist** [comment]
Still working on getting CircleCI configured on my branch. They appear to have some bugs associated with running parallel builds on different versions of the JDK. On a positive note - their tech support is helping me craft a custom circle.yml file

**Comment by buildscientist** [comment]
At this point I'm not sure if CircleCI supports simultaneous builds across different versions of the JDK. Still working through the details with CircleCI support. We might need to stick with Travis.

**Comment by buildscientist** [comment]
Never mind - looks like I got it to work. A lot of these cloud CI providers use these yucky declarative config files to setup build workflows :-1:  

I'll need to clean it up - but here's what I've got so far: 

```yaml
general:
 build_dir: ./

test:
 override:
 - sudo update-alternatives --set java "/usr/lib/jvm/jdk1.7.0/bin/java"
 - sudo update-alternatives --set javac "/usr/lib/jvm/jdk1.7.0/bin/javac"
 - mvn install -DskipTests
 - mvn test
 - sudo update-alternatives --set java "/usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java"
 - sudo update-alternatives --set javac "/usr/lib/jvm/java-7-openjdk-amd64/bin/javac"
 - mvn clean install -DskipTests
 - mvn test
```

I am noticing that some of the tests aren't shutting down the GreenMail service properly so I'll need to go in there and clean those up.
